In [3]:
import numpy as np

a = np.random.randn(1,3)
b = np.random.randn(3,3)
c = a*b
print(c.shape)

(3, 3)


In [11]:
a = np.random.randn(1,3)
b = np.random.randn(3,3)
c = a*b
print(c.shape)

(3, 3)


In [4]:
import numpy as np

x = np.array([[2, 1], [1, 3]])
b = np.dot(x, x)
print(b)


[[ 5  5]
 [ 5 10]]


In [2]:
import numpy as np

x = np.array([[[1], [2]], [[3], [4]]])
print(x.shape)

(2, 2, 1)


In [12]:
a = np.random.randn(4,3)
b = np.random.randn(4,1)

print(a)
d = a**2
print(d)

[[ 0.36033333  2.04193004  0.20376758]
 [-0.83023173  0.91073644 -0.82630909]
 [-0.27740347 -1.77695348 -0.83287353]
 [ 0.4458747  -0.44598371  1.21790673]]
[[0.12984011 4.16947828 0.04152123]
 [0.68928473 0.82944086 0.68278671]
 [0.07695268 3.15756365 0.69367832]
 [0.19880425 0.19890147 1.4832968 ]]


In [8]:
a = np.array([[2, 1], [1, 3],  [1, 3]])

print(a)

print(a.T)

[[2 1]
 [1 3]
 [1 3]]
[[2 1 1]
 [1 3 3]]
